<a href="https://colab.research.google.com/github/VASAVI1231/numpy-data-filtering/blob/main/numpy_data_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a NumPy array of student marks
marks = np.array([35, 48, 52, 67, 75, 81, 90, 43, 58, 29])

print("Original Marks:")
print(marks)

# Boolean conditions
condition_above_50 = marks > 50
condition_below_50 = marks < 50
condition_equal_50 = marks == 50

print("\nBoolean condition - Above 50:")
print(condition_above_50)

print("\nBoolean condition - Below 50:")
print(condition_below_50)

print("\nBoolean condition - Equal to 50:")
print(condition_equal_50)

# Boolean indexing / filtering
above_50 = marks[marks > 50]
below_50 = marks[marks < 50]
equal_50 = marks[marks == 50]

print("\nValues Above 50:")
print(above_50)

print("\nValues Below 50:")
print(below_50)

print("\nValues Equal to 50:")
print(equal_50)

# Different thresholds
above_60 = marks[marks > 60]
below_40 = marks[marks < 40]
greater_equal_75 = marks[marks >= 75]
less_equal_50 = marks[marks <= 50]

print("\nValues Above 60:")
print(above_60)

print("\nValues Below 40:")
print(below_40)

print("\nValues Greater Than or Equal to 75:")
print(greater_equal_75)

print("\nValues Less Than or Equal to 50:")
print(less_equal_50)

Original Marks:
[35 48 52 67 75 81 90 43 58 29]

Boolean condition - Above 50:
[False False  True  True  True  True  True False  True False]

Boolean condition - Below 50:
[ True  True False False False False False  True False  True]

Boolean condition - Equal to 50:
[False False False False False False False False False False]

Values Above 50:
[52 67 75 81 90 58]

Values Below 50:
[35 48 43 29]

Values Equal to 50:
[]

Values Above 60:
[67 75 81 90]

Values Below 40:
[35 29]

Values Greater Than or Equal to 75:
[75 81 90]

Values Less Than or Equal to 50:
[35 48 43 29]
